sonar.projectKey=shopware
sonar.sources=plugin/MessengerHistoryDashboard/src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=plugin/MessengerHistoryDashboard/src/Resources/public/**
sonar.coverage.exclusions=plugin/MessengerHistoryDashboard/src/Resources/app/administration/src/module/mh-dashboard/page/**/*.js
sonar.cpd.exclusions=plugin/MessengerHistoryDashboard/src/Resources/app/administration/src/module/mh-dashboard/page/**/*.js,tests/**/*.php
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
