
services:
###> shopware/core ###
  database:
    ports:
      - "3306"
###< shopware/core ###

###> xdebug ###
  web:
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug,develop
###< xdebug ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> shopware/elasticsearch ###
  opensearch:
    ports:
      - "9200"
###< shopware/elasticsearch ###
